-- @testpoint: 表达式做为参数的存储过程测试--类型转换-IF(,,) 合理报错

--创建存储过程
CREATE OR REPLACE PROCEDURE FVT_PROC_EXPR_PARAM_022(T1 CHAR)  AS
BEGIN
raise info 'T1=:%',T1;
EXCEPTION
WHEN NO_DATA_FOUND THEN raise info'NO_DATA_FOUND';
END;
/
--调用存储过程
CALL FVT_PROC_EXPR_PARAM_022(IF(2>1,'a','b'));
CALL FVT_PROC_EXPR_PARAM_022(IFNULL('a','b'));
CALL FVT_PROC_EXPR_PARAM_022(IFNULL(NULL,'b'));
--清理环境
drop PROCEDURE FVT_PROC_EXPR_PARAM_022;