-- @testpoint: 表达式做为参数的存储过程测试--函数表达式-数值计算函数-ABS(exp)

--创建存储过程
CREATE OR REPLACE PROCEDURE PROC_EXPR_PARAM_006(P1 BIGINT)  AS
BEGIN
raise info 'P1=:%',P1;
EXCEPTION
WHEN NO_DATA_FOUND THEN raise info 'NO_DATA_FOUND';
END;
/
--调用存储过程
DECLARE
V1 INT :=ABS(-1234);
BEGIN
 PROC_EXPR_PARAM_006(V1);
END;
/
--调用存储过程
DECLARE
V1 BIGINT :=ABS(2475866945);
BEGIN
 PROC_EXPR_PARAM_006(V1);
END;
/
--清理环境
drop PROCEDURE PROC_EXPR_PARAM_006;
