-- @testpoint: 表达式做为参数的存储过程测试--函数表达式-MOD(x,y)

--创建存储过程
CREATE OR REPLACE PROCEDURE PROC_EXPR_PARAM_012(P1 DECIMAL,P2 DECIMAL,P3 OUT DECIMAL)  AS
BEGIN
P3:=MOD(P1,P2);
raise info 'P3=:%',P3;
EXCEPTION
WHEN NO_DATA_FOUND THEN raise info 'NO_DATA_FOUND';
END;
/
--调用存储过程
DECLARE
V1 INT :=9;
V2 INT :=3;
V3 DECIMAL;
BEGIN
 PROC_EXPR_PARAM_012(V1,V2,V3);
END;
/
--调用存储过程
DECLARE
V4 DECIMAL :=100;
V5 DECIMAL :=52;
V6 DECIMAL;
BEGIN
 PROC_EXPR_PARAM_012(V4,V5,V6);
END;
/
--调用存储过程
DECLARE
V7 DECIMAL :=896.3;
V8 DECIMAL :=4.7;
V9 DECIMAL;
BEGIN
 PROC_EXPR_PARAM_012(V7,V8,V9);
END;
/
--清理环境
drop PROCEDURE PROC_EXPR_PARAM_012;