-- @testpoint: 表达式做为参数的存储过程测试——字符串处理函数-HEX()

--创建存储过程
CREATE OR REPLACE PROCEDURE PROC_EXPR_PARAM_017(P1 CHAR ,P2 INT,T1 OUT VARCHAR,T2 OUT VARCHAR2)  AS
BEGIN
T1:=TO_HEX(P1);
raise info'T1=:%',T1;
T2:=TO_HEX(P2);
raise info 'T2=:%',T2;
EXCEPTION
WHEN NO_DATA_FOUND THEN raise info 'NO_DATA_FOUND';
END;
/
--调用存储过程
DECLARE
V1 VARCHAR(50):='23443557';
V2 INT:=978;
V3 VARCHAR(400); 
V4 VARCHAR(400);   
BEGIN
PROC_EXPR_PARAM_017(V1,V2,V3,V4);
END;
/
--清理环境
drop PROCEDURE PROC_EXPR_PARAM_017;