-- @testpoint: 表达式做为参数的存储过程测试——类型转换-CHR(),CHAR()

--创建存储过程
CREATE OR REPLACE PROCEDURE PROC_EXPR_PARAM_020(P1 CHAR)  AS
BEGIN
raise info 'P1=:%',P1;
EXCEPTION
WHEN NO_DATA_FOUND THEN raise info 'NO_DATA_FOUND';
END;
/
--调用存储过程
DECLARE
V1 CHAR :=CHR(65);
BEGIN
PROC_EXPR_PARAM_020(V1);
END;
/
--调用存储过程
DECLARE
V2 CHAR (64);
BEGIN
PROC_EXPR_PARAM_020(V2);
END;
/
--清理环境
drop  PROCEDURE PROC_EXPR_PARAM_020;