-- @testpoint: 约束名为64位（opengauss中没有明确长度限制，所以现在超出长度会截断并不会报错）


DROP TABLE IF EXISTS tal_09;
CREATE TABLE tal_09( C_CHAR20 CHAR(20) not null, C_INT INT);
ALTER TABLE tal_09 ADD CONSTRAINT BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB64 UNIQUE(C_INT);
INSERT INTO tal_09 VALUES('2020-07-06',53);
INSERT INTO tal_09 VALUES('2020-07-06',369);
ALTER TABLE tal_09 DROP CONSTRAINT  IF EXISTS BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB64 CASCADE ;
DROP TABLE IF EXISTS tal_09;

