-- @testpoint: 表名有特殊字符合理报错

DROP TABLE IF EXISTS BBA@AAAAAAAAAAAAAA！AAAAAAAAAAAAAAAA#AAAAAAAAAAA好AAAAAABBB63;
CREATE TABLE BBA@AAAAAAAAAAAAAA！AAAAAAAAAAAAAAAA#AAAAAAAAAAA好AAAAAABBB63( BAAABBB63 CHAR(20) PRIMARY KEY,ID int);
INSERT INTO BBA@AAAAAAAAAAAAAA！AAAAAAAAAAAAAAAA#AAAAAAAAAAA好AAAAAABBB63 VALUES('2012-07-12',789);
INSERT INTO BBA@AAAAAAAAAAAAAA！AAAAAAAAAAAAAAAA#AAAAAAAAAAA好AAAAAABBB63 VALUES('2013-07-12',852);
INSERT INTO BBA@AAAAAAAAAAAAAA！AAAAAAAAAAAAAAAA#AAAAAAAAAAA好AAAAAABBB63 VALUES('2014-07-12',453);


