-- @testpoint: 约束名为63位
DROP TABLE IF EXISTS tal_01;
CREATE TABLE tal_01( C_CHAR20 CHAR(20) not null, C_INT INT);
ALTER TABLE tal_01 ADD CONSTRAINT BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB63 UNIQUE(C_INT);
INSERT INTO tal_01 VALUES('2020-07-06',53);
INSERT INTO tal_01 VALUES('2020-07-06',369);
ALTER TABLE tal_01 DROP CONSTRAINT  IF EXISTS BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBB63 CASCADE ;
DROP TABLE IF EXISTS tal_01;