package com.huawei.gauss.yat.setting

const val YAT_HOME_ENV = "YAT_HOME"
const val CONST_CONFIG_YML_FILE = "configure.yml"
const val CONST_NODES_YML_FILE = "nodes.yml"
const val CONST_CONFIG_DIR = "conf"
const val CONST_PROGRAM_NAME = "yat"
const val CONST_SCHEDULE_SCHD_FILE = "schedule.schd"
const val CONST_SCHEDULE_YAT_FILE = "schedule.yat"
const val CONST_TESTCASE_DIR = "testcase"
const val CONST_LIBRARY_DIR = "lib"
const val CONST_RESULT_DIR = "result"
const val CONST_EXPECT_DIR = "expect"
const val CONST_SCHEDULE_DIR = "schedule"
const val CONST_MACRO_YML_FILE = "macro.yml"
const val CONST_TEMP_DIR = "temp"
const val CONST_LOG_DIR = "log"
const val CONST_LOG_TEXT_NAME = "yat.log"
const val CONST_LOG_JSON_NAME = "yat.json"
const val CONST_LOG_REDO_NAME = "yat.redo"
const val CONST_LOCK_FILE = ".lock"
const val CONST_SUITE_DIR = "YAT_SUITE_DIR"
const val CONST_SUITE_TMP = "YAT_SUITE_TMP"
const val CONST_RUN_SUITE = "RUN_SUITE"
const val CONST_CONTEXT_NAME = "context.yml"
