-- @testpoint:选择不存在的数据库，部分用例合理报错
use sch_Opengauss_DATABASE_Case0002_1;
select database();
use sch_Opengauss_DATABASE_Case0002_2;
select database();
use sch_Opengauss_DATABASE_Case0002_3;
select database();
use public;
select database();
use sch_Opengauss_DATABASE_Case0002_4;
select database();
