-- @testpoint: 标量类型%type的测试———列属性改变
drop table if exists FVT_PROC_SCALAR_TYPE_table_007;
CREATE TABLE FVT_PROC_SCALAR_TYPE_table_007(
  T1 INT,
  T22 BOOL
) ;

create unique index  FVT_PROC_SCALAR_TYPE_table_index_007 on FVT_PROC_SCALAR_TYPE_table_007(T1);

--创建存储过程
CREATE OR REPLACE PROCEDURE FVT_PROC_SCALAR_TYPE_007(P1 FVT_PROC_SCALAR_TYPE_table_007.T22%type)  AS
BEGIN
raise info 'P1=:%',P1;
EXCEPTION
WHEN NO_DATA_FOUND THEN raise info 'NO_DATA_FOUND';
END;
/

--调用存储过程
DECLARE
x1 FVT_PROC_SCALAR_TYPE_table_007.T22%type :=1234;
BEGIN
FVT_PROC_SCALAR_TYPE_007(x1);
END;
/

--修改列属性
alter table FVT_PROC_SCALAR_TYPE_table_007 modify T22 INT;

--重新编译存储过程
CREATE OR REPLACE PROCEDURE FVT_PROC_SCALAR_TYPE_007_CS7(P1 FVT_PROC_SCALAR_TYPE_table_007.T22%type)  AS
BEGIN
raise info 'P1=:%',P1;
EXCEPTION
WHEN NO_DATA_FOUND THEN raise info 'NO_DATA_FOUND';
END;
/

--调用存储过程
DECLARE
x2 FVT_PROC_SCALAR_TYPE_table_007.T22%type :=12345;
BEGIN
FVT_PROC_SCALAR_TYPE_007_CS7(x2);
END;
/

DROP PROCEDURE FVT_PROC_SCALAR_TYPE_007_CS7;
drop table if exists FVT_PROC_SCALAR_TYPE_table_007;
DROP PROCEDURE FVT_PROC_SCALAR_TYPE_007;