-- @testpoint: RANGE分区表
drop table if exists tp2;
CREATE TABLE tp2
(
c_ID INT  NOT NULL,
c_D_ID INT NOT NULL,
c_W_ID INT NOT NULL,
c_FIRST VARCHAR(32) NOT NULL,
c_MIDDLE CHAR(2),
c_LAST VARCHAR(32) NOT NULL,
c_STREET_1 VARCHAR(40) NOT NULL,
c_STREET_2 VARCHAR(40),
c_CITY VARCHAR(40) NOT NULL,
c_STATE CHAR(2) NOT NULL,
c_ZIP CHAR(9) NOT NULL,
c_PHONE CHAR(32) NOT NULL,
c_SINCE TIMESTAMP,
c_CREDIT CHAR(2) NOT NULL,
c_CREDIT_LIM NUMERIC(12,2),
c_DISCOUNT NUMERIC(4,4),
c_BALANCE NUMERIC(12,2),
c_YTD_PAYMENT REAL NOT NULL,
c_PAYMENT_CNT NUMBER NOT NULL,
c_DELIVERY_CNT BOOL NOT NULL,
c_END DATE NOT NULL,
c_VCHAR VARCHAR(1000),
c_data clob,
c_text blob
)
PARTITION BY RANGE(c_ID,c_FIRST,c_LAST)
(
PARTITION PART_1 VALUES LESS THAN (101,'B','B'),
PARTITION PART_2 VALUES LESS THAN (201,'C','C'),
PARTITION PART_3 VALUES LESS THAN (301,'D','D'),
PARTITION PART_4 VALUES LESS THAN (401,'E','E'),
PARTITION PART_5 VALUES LESS THAN (501,'F','F'),
PARTITION PART_6 VALUES LESS THAN (601,'G','G'),
PARTITION PART_7 VALUES LESS THAN (701,'H','H'),
PARTITION PART_8 VALUES LESS THAN (801,'I','I'),
PARTITION PART_9 VALUES LESS THAN (901,'J','J'),
PARTITION PART_10 VALUES LESS THAN (1001,'K','K'),
PARTITION PART_11 VALUES LESS THAN (1101,'L','L'),
PARTITION PART_12 VALUES LESS THAN (1201,'M','M'),
PARTITION PART_13 VALUES LESS THAN (MAXVALUE,MAXVALUE,MAXVALUE)
);
drop table tp2;