-- @testpoint: rawtohex函数用于创建视图的列
DROP TABLE IF EXISTS TEST_RAWTOHEX;
CREATE TABLE TEST_RAWTOHEX(A INT,B varchar2(20));
INSERT INTO TEST_RAWTOHEX VALUES(1,'CERTPIC');
INSERT INTO TEST_RAWTOHEX VALUES(2,'CEC');
INSERT INTO TEST_RAWTOHEX VALUES(3,'aa');
CREATE OR REPLACE VIEW V_TEST_RAWTOHEX as SELECT A,TO_CHAR(rawtohex(SUBSTR(B, 2, 1))) tt from TEST_RAWTOHEX order by A ;
SELECT * FROM V_TEST_RAWTOHEX order by A;
drop view V_TEST_RAWTOHEX;
DROP TABLE IF EXISTS TEST_RAWTOHEX;