-- @testpoint: 建分区表char类型，默认1024个字符

drop table if exists tbl_04;
create table tbl_04(
id integer,
c_varchar char(1025) not null default 'aaaaaaadddsfdsfdsfdfsfdsffffffffffffffffffssssdsdsadsdddddddddddsdsdsdsdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddsfdsfdsfdfsfdsffffffffffffffffffssssdsdsadsdddddddddddsdsdsdsdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddsfdsfdsfdfsfdsffffffffffffffffffssssdsdsadsdddddddddddsdsdsdsdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddsfdsfdsfdfsfdsffffffffffffffffffssssdsdsadsdddddddddddsdsdsdsdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddsfdsfdsfdfsfdsffffffffffffffffffssssdsdsadsdddddddddddsdsdsdsdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddsfdsfdsfdfsfdsffffffffffffffffffssssdsdsadsdddddddddddsdsdsdsdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadddsfdsfdsfdfsfdsffffffffffffffffffssssdsdsadsdddddddddddsdsdsdsdaaaabc12') 
partition by range(id)
(
partition part1 values less than (10),
partition part values less than(100),
partition part3 values less than(1000),
partition part4 values less than(maxvalue)
);
insert into tbl_04 values (1,default);
 select * from tbl_04;
drop table tbl_04;