-- @testpoint: 增加字段用默认值，先default后null
DROP TABLE IF EXISTS META_ENUM;
CREATE TABLE IF NOT EXISTS META_ENUM 
(ID BIGINT NOT NULL,
 ATTR_ID BIGINT NULL,
 NAME VARCHAR(60) NOT NULL,
   VALUE_LIST VARCHAR(1000),
   I18N_LIST VARCHAR(2000),
   PRIMARY KEY (ID))
;
ALTER TABLE META_ENUM ADD COLUMN location2 VARCHAR(255) DEFAULT 'common' NULL;
DROP TABLE META_ENUM;
