-- @testpoint: 创建带DEFERRABLE INITIALLY IMMEDIATE约束的表，并设置约束在每条语句后进行检查，有违背时合理报错
START TRANSACTION;
SET CONSTRAINTS ALL DEFERRED;
DROP TABLE IF EXISTS tab_18;
CREATE TABLE IF not EXISTS tab_18
(id      NUMBER(7)PRIMARY KEY DEFERRABLE INITIALLY IMMEDIATE,
name       VARCHAR2(20)
);
insert into tab_18 values(1,'小龙');
insert into tab_18 values(1,'小牛');
SET CONSTRAINTS all IMMEDIATE;
DROP TABLE IF EXISTS tab_18 CASCADE;
COMMIT;