-- @testpoint: 修改字段类型为CHAR
DROP TABLE IF EXISTS t_blob;
CREATE TABLE t_blob(ID BLOB);
INSERT INTO t_blob VALUES('35466');
INSERT INTO t_blob VALUES('100000');
INSERT INTO t_blob VALUES('C4711A1097876CC');
INSERT INTO t_blob VALUES('');
INSERT INTO t_blob VALUES(NULL);
COMMIT;
ALTER TABLE T_BLOB MODIFY (ID CHAR(50));
ALTER TABLE T_BLOB MODIFY (ID VARCHAR(50));
UPDATE T_BLOB SET ID=NULL;
ALTER TABLE T_BLOB MODIFY (ID CHAR(50));
ALTER TABLE T_BLOB MODIFY (ID VARCHAR(50));
DELETE FROM T_BLOB;
ALTER TABLE T_BLOB MODIFY (ID CHAR(50));
ALTER TABLE T_BLOB MODIFY (ID VARCHAR(50));
drop table if exists t_blob;