-- @testpoint: 自然对数lnx使用查询的函数值创建视图
drop view if exists V_TEST_LN;
DROP TABLE IF EXISTS TEST_LN;
CREATE TABLE TEST_LN(A INT,B INT);
INSERT INTO TEST_LN VALUES(0,1);
INSERT INTO TEST_LN VALUES(1,4);
INSERT INTO TEST_LN VALUES(0.5,2);
CREATE OR REPLACE VIEW V_TEST_LN AS SELECT LN(B) tt FROM TEST_LN;
SELECT * FROM  V_TEST_LN order by tt;
drop view if exists V_TEST_LN;
DROP TABLE IF EXISTS TEST_LN;