-- @testpoint: max函数与groupby orderby联用
drop table if exists SYS_FUNCTION_MAX_TABLE2;
CREATE TABLE  SYS_FUNCTION_MAX_TABLE2(COL_ID INTEGER,COL_PLACE char(40),COL_MONEY number);
INSERT INTO SYS_FUNCTION_MAX_TABLE2 (COL_ID,COL_PLACE,COL_MONEY) VALUES (1,'gansu',2.4),(2,'xinjiang',3.5),(6,'gansu',6.6);
SELECT COL_PLACE , MAX(COL_ID)AS MAX_ID,MAX(COL_MONEY)AS MAX_MONEY FROM SYS_FUNCTION_MAX_TABLE2 GROUP BY COL_PLACE ORDER BY COL_PLACE,MAX_ID,MAX_MONEY;
drop table if exists SYS_FUNCTION_MAX_TABLE2;