-- @testpoint: max函数用于select语句
drop table if exists SYS_FUNCTION_MAX_TABLE1;
CREATE TABLE  SYS_FUNCTION_MAX_TABLE1(COL_ID INTEGER,COL_PLACE char(40),COL_MONEY number) ;
INSERT INTO SYS_FUNCTION_MAX_TABLE1 (COL_ID,COL_PLACE,COL_MONEY) VALUES (1,'gansu',2.5),(2,'xinjiang',3.5),(6,'gansu',6.3);
SELECT MAX(COL_ID)AS RESULT1,MAX(COL_MONEY)AS RESULT2 FROM SYS_FUNCTION_MAX_TABLE1;
drop table if exists SYS_FUNCTION_MAX_TABLE1;