-- @testpoint: max函数与having联用
drop table if exists SYS_FUNCTION_MAX_TABLE20;
CREATE TABLE  SYS_FUNCTION_MAX_TABLE20(INT1 INTEGER,int INTEGER,INT3 INTEGER) ;
INSERT INTO SYS_FUNCTION_MAX_TABLE20 VALUES (1,1,1),(2,2,1),(2,2,2),(3,4,2),(3,3,3),(4,5,3);
SELECT INT3 AS RESULT1,MAX(INT1)AS RESULT2,MAX(int)AS RESULT3 FROM SYS_FUNCTION_MAX_TABLE20 GROUP BY INT3  HAVING MAX(INT1)=4;
drop table if exists SYS_FUNCTION_MAX_TABLE20;