-- @testpoint: covar_samp函数返回结果用于create table as select
drop table if exists T_VAR_POP_SAMP_VARIANCE01;
CREATE TABLE  T_VAR_POP_SAMP_VARIANCE01(
     COL_1 integer,
     COL_2 number(19,0), 
     COL_3 number(10,6));
insert into T_VAR_POP_SAMP_VARIANCE01 values(7,312.245,7+445.255);
insert into T_VAR_POP_SAMP_VARIANCE01 values(5,112.245,7+443.255);
DROP TABLE IF EXISTS T_VAR_SAMP_DEFALUT03;
CREATE TABLE T_VAR_SAMP_DEFALUT03 as SELECT covar_samp(COL_2,COL_2) as a FROM T_VAR_POP_SAMP_VARIANCE01 group by COL_1,COL_2,COL_3; 
select * from T_VAR_SAMP_DEFALUT03 order by 1;
DROP TABLE IF EXISTS T_VAR_SAMP_DEFALUT03;
CREATE TABLE T_VAR_SAMP_DEFALUT03 as SELECT covar_samp(COL_2-COL_3,COL_2-COL_3) as a FROM T_VAR_POP_SAMP_VARIANCE01;
select * from T_VAR_SAMP_DEFALUT03 order by 1;
DROP TABLE IF EXISTS T_VAR_SAMP_DEFALUT03;
drop table if exists T_VAR_POP_SAMP_VARIANCE01;