-- @testpoint: recode复合类型正常使用情况，执行成功

drop table if exists SF_ORG;
CREATE TABLE SF_ORG
(
ORG_ID INT NOT NULL, 
ORG_NAME VARCHAR2(50),
PARENT_ID INT
);

INSERT INTO SF_ORG(ORG_ID, ORG_NAME, PARENT_ID) VALUES(1, '一级部门1',0);
INSERT INTO SF_ORG(ORG_ID, ORG_NAME, PARENT_ID) VALUES(2, '二级部门2',1);
INSERT INTO SF_ORG(ORG_ID, ORG_NAME, PARENT_ID) VALUES(3, '二级部门3',1);
INSERT INTO SF_ORG(ORG_ID, ORG_NAME, PARENT_ID) VALUES(4, '二级部门4',1);

DECLARE 
  TYPE TYPE_ORG_RECORD IS RECORD(
  V_ORG_NAME SF_ORG.ORG_NAME%TYPE,
  V_PARENT_ID SF_ORG.PARENT_ID%TYPE);
  V_ORG_RECORD TYPE_ORG_RECORD;
BEGIN
  SELECT ORG_NAME,PARENT_ID INTO V_ORG_RECORD
  FROM SF_ORG SO
  WHERE SO.ORG_ID=2;
  raise info '部门名称:%',V_ORG_RECORD.V_ORG_NAME;
  raise info '上级部门编码:%',TO_CHAR(V_ORG_RECORD.V_PARENT_ID);
END;
/
drop table SF_ORG;